# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Deploy HOME module
      working-directory: applications/home
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build & Deploy SEARCH module
      working-directory: applications/search
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build & Deploy CHECKOUT module
      working-directory: applications/checkout
      run: |
        npm install
        npm run build
      env:
        CI: true